export default [
    {
        id: 1,
        clothImg: "images/shop1.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id:2,
        clothImg: "images/shop5.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$450.99",
        slash: "$600.99",
        percent: "-7%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id:3,
        clothImg: "images/shop6.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$750.99",
        slash: "$800.99",
        percent: "-5%",
        starRating: "",
        reviewCount: "92",
    },
    {
        id:4,
        clothImg: "images/shop4.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$920.99",
        slash: "$989.99",
        percent: "-9%",
        starRating: "",
        reviewCount: "12",
    },
    {
        id:5,
        clothImg: "images/shop7.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$450.99",
        slash: "$600.99",
        percent: "-7%",
        starRating: "",
        reviewCount: "299", 
    },
    {
        id:6,
        clothImg: "images/shop3.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$450.99",
        slash: "$600.99",
        percent: "-7%",
        starRating: "",
        reviewCount: "299", 
    },
    {
        id:7,
        clothImg: "images/shop2.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$450.99",
        slash: "$600.99",
        percent: "-7%",
        starRating: "",
        reviewCount: "299", 
    }




]