export default [
    {
        id: 1,
        clothImg: "images/1.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id:2,
        clothImg: "images/2.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$450.99",
        slash: "$600.99",
        percent: "-7%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id:3,
        clothImg: "images/3.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$750.99",
        slash: "$800.99",
        percent: "-5%",
        starRating: "",
        reviewCount: "92",
    },
    {
        id:4,
        clothImg: "images/4.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$920.99",
        slash: "$989.99",
        percent: "-9%",
        starRating: "",
        reviewCount: "12",
    },
    {
        id:5,
        clothImg: "images/5.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$450.99",
        slash: "$600.99",
        percent: "-7%",
        starRating: "",
        reviewCount: "299", 
    },
    {
        id: 6,
        clothImg: "images/6.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id: 7,
        clothImg: "images/7.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id: 8,
        clothImg: "images/8.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id: 9,
        clothImg: "images/9.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id: 10,
        clothImg: "images/10.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id: 11,
        clothImg: "images/11.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id: 12,
        clothImg: "images/12.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id: 13,
        clothImg: "images/13.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id: 14,
        clothImg: "images/14.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
    {
        id: 15,
        clothImg: "images/15.jpg",
        clothText: "Mens Casual Winter Jacket Pack Of Two(Orange)",
        price: "$950.99",
        slash: "$999.99",
        percent: "-4%",
        starRating: "",
        reviewCount: "299",
    },
]